# Generated by Django 5.2.10 on 2026-01-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_fcregister', models.DateField(auto_now_add=True)),
                ('fit_weight', models.FloatField(default=0.0)),
                ('fit_fccrea', models.DateTimeField(auto_now=True)),
                ('fit_user_crea', models.CharField(max_length=100)),
                ('fit_fc_modi', models.DateTimeField(auto_now=True)),
                ('fit_user_modi', models.CharField(max_length=100)),
                ('fit_estado', models.BooleanField(default=False)),
                ('fit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fit_fccrea'],
            },
        ),
    ]
