# Generated by Django 5.2.10 on 2026-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='fit_fcregister',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='fit_user_modi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
