# Generated by Django 5.2.10 on 2026-01-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboard_fit_fcregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='fit_user_modi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
