# Generated by Django 5.2.10 on 2026-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboard_fit_user_modi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fit_observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
