# Generated by Django 5.2.10 on 2026-01-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_fit_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='fit_observation',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
