# Generated by Django 5.2.10 on 2026-01-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_fit_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='fit_user',
            new_name='user',
        ),
    ]
