# Generated by Django 5.2.10 on 2026-01-21 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_prof_phne', models.CharField(max_length=20)),
                ('fit_prof_birth_date', models.DateField()),
                ('fit_prof_avatar', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fit_prof_fc_crea', models.DateTimeField(auto_now_add=True)),
                ('fit_prof_fc_modi', models.DateTimeField(auto_now=True)),
                ('fit_prof_height', models.PositiveBigIntegerField(default=0)),
                ('fit_prof_weight', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitprofiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fit_prof_fc_crea'],
                'unique_together': {('fit_prof_phne',)},
            },
        ),
    ]
