# Generated by Django 5.2.10 on 2026-01-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitprofile', '0002_alter_fitprofile_fit_prof_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitprofile',
            name='fit_sexo',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
