# Generated by Django 5.2.10 on 2026-01-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitprofile', '0004_alter_fitprofile_fit_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='fit_sexo',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
