# Generated by Django 5.2.10 on 2026-01-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitprofile', '0005_alter_fitprofile_fit_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='fit_sexo',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
