# Generated by Django 5.2.10 on 2026-01-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitprofile', '0006_alter_fitprofile_fit_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='fit_prof_phne',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fitprofile',
            name='fit_sexo',
            field=models.CharField(blank=True, choices=[('', 'Selecciones un genero'), ('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
