# Generated by Django 5.2.10 on 2026-01-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitprofile', '0007_alter_fitprofile_fit_prof_phne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitprofile',
            name='fit_prof_phne',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
